./hash_normal_test
./hdel_general_test
./hgetall_general_test
./hget_general_test
./hmget_general_test
./hmset_general_test
./hset_general_test
./sadd_general_test
./set_normal_test
./smembers_general_test
./srem_general_test
./list_interface_test
./zadd_generic_test
./zcard_generic_test
./zrem_generic_test
./zrange_generic_test
./zrangebyscore_generic_test
./zremrangebyrank_generic_test
./test_test_helper
